In [1]:
import numpy as np

# performance comparison
my_list = list(range(1000000))
my_arr = np.arange(1000000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [2]:
%time for _ in range(10): [x*2 for x in my_list]

CPU times: user 352 ms, sys: 118 ms, total: 471 ms
Wall time: 467 ms


In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2  # element-wise operation
# python -> numpy ::: 10-100x performance

CPU times: user 30.5 ms, sys: 10 ms, total: 40.5 ms
Wall time: 36.6 ms


In [5]:
data = np.random.randn(2, 3)   # shape
data

array([[ 0.10995475,  0.44812622, -0.51027866],
       [-1.68305358, -0.96509436, -1.2600814 ]])

In [6]:
data * 10  # mul element-wise

array([[  1.0995475 ,   4.48126221,  -5.10278658],
       [-16.83053582,  -9.65094363, -12.60081397]])

In [7]:
data + 1000

array([[1000.10995475, 1000.44812622,  999.48972134],
       [ 998.31694642,  999.03490564,  998.7399186 ]])

In [8]:
1 / data

array([[ 9.09465028,  2.23151414, -1.95971355],
       [-0.59415815, -1.03616811, -0.79359953]])

In [9]:
data  

array([[ 0.10995475,  0.44812622, -0.51027866],
       [-1.68305358, -0.96509436, -1.2600814 ]])

In [10]:
data * 2

array([[ 0.2199095 ,  0.89625244, -1.02055732],
       [-3.36610716, -1.93018873, -2.52016279]])

In [11]:
data + data  # matrix sum

array([[ 0.2199095 ,  0.89625244, -1.02055732],
       [-3.36610716, -1.93018873, -2.52016279]])

In [12]:
print(data.dtype, type(data.dtype))
print(data.shape, type(data.shape))

float64 <class 'numpy.dtype[float64]'>
(2, 3) <class 'tuple'>


In [15]:
# various creating ways
data1 = [1, 2, 3, 4, -1.2]
arr1 = np.array(data1)
arr1.dtype

dtype('float64')

In [17]:
data2 = [[1, 2, 3], [-1, -2, -3]]
arr2 = np.array(data2)
arr2

array([[ 1,  2,  3],
       [-1, -2, -3]])

In [18]:
arr2.dtype

dtype('int64')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
np.empty((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.empty(5)  # no guarantee that it is 0

array([1. , 2. , 3. , 4. , 1.2])

In [25]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
np.arange(5, 39, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [28]:
arr = np.array([1, 2, 3], dtype=np.float64)
arr.dtype

dtype('float64')

In [29]:
np.string_

numpy.bytes_

In [34]:
np.array(['hello', 'world'])

array(['hello', 'world'], dtype='<U5')

In [37]:
# Casting
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr)
string_arr = arr.astype(np.unicode_)
print(string_arr)

int64
[1. 2. 3. 4.]
['1' '2' '3' '4']


In [39]:
arr = np.array([1.4, 3.9, -1.2, 5])
print(arr)
print(arr.astype(np.int32))  # truncated!

[ 1.4  3.9 -1.2  5. ]
[ 1  3 -1  5]


In [40]:
arr = np.arange(10)
other_arr = np.array([1.2, -3.2, 0])
arr.astype(other_arr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
#
# Basic arithmetic
#
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype='f8')  # 8bytes -> 64bits -> np.float64
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
arr + arr  # matrix sum (same as element-wise)

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [44]:
arr * arr  # vectorization --> operations without the loop  --> element-wise (same shape)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
2**5

32

In [47]:
arr**2.3

array([[ 1.        ,  4.92457765, 12.51350253],
       [24.25146506, 40.51641492, 61.62371494]])

In [50]:
other_arr = np.array([[0, -2, 3], [0, 19, -123]])
print(arr)
print(other_arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[   0   -2    3]
 [   0   19 -123]]


In [49]:
arr > other_arr

array([[ True,  True, False],
       [ True, False,  True]])

In [52]:
#
# indexing
#
arr = np.arange(10)
print(arr)
arr[5]

[0 1 2 3 4 5 6 7 8 9]


5

In [53]:
arr[2:5]

array([2, 3, 4])

In [54]:
arr[1] = 212121231

In [55]:
arr

array([        0, 212121231,         2,         3,         4,         5,
               6,         7,         8,         9])

In [57]:
arr[:4] = -1
arr

array([-1, -1, -1, -1,  4,  5,  6,  7,  8,  9])

In [58]:
slice = arr[5:]
slice

array([5, 6, 7, 8, 9])

In [59]:
slice[1] = 1000
print(slice)
print(arr)

[   5 1000    7    8    9]
[  -1   -1   -1   -1    4    5 1000    7    8    9]


In [60]:
slice[:] = 0
arr

array([-1, -1, -1, -1,  4,  0,  0,  0,  0,  0])

In [63]:
new_arr = arr[:3].copy()
new_arr

array([-1, -1, -1])

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr[0]

array([1, 2, 3])

In [66]:
arr[0][1]

2

In [67]:
arr[0, 1]

2

In [68]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr[1] = np.arange(3)
arr

array([[1, 2, 3],
       [0, 1, 2]])

In [70]:
arr[:2]

array([[1, 2, 3],
       [0, 1, 2]])

In [73]:
arr = np.array([list(range(i, 5+i)) for i in range(5)])
arr

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [76]:
arr[:2, 3:] = 10
arr

array([[ 0,  1,  2, 10, 10],
       [ 1,  2,  3, 10, 10],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8]])

In [77]:
names = np.array(['Pedro', 'Goncalo', 'Maria', 'Maria', 'Pedro', 'Joao', 'Pedro'])
names.shape

(7,)

In [78]:
data = np.random.randn(7, 4)
data

array([[ 2.83436822, -0.39655303,  0.22610492, -0.77144254],
       [-0.63763841, -0.43784856, -0.35788553, -0.02061979],
       [ 0.83591948,  0.03121459,  1.07320361, -0.94190559],
       [ 0.36530313,  0.29042613,  0.4468085 , -1.47401516],
       [ 0.72924946, -1.30924418,  0.32784375, -0.65750778],
       [ 0.74913359, -0.99250194, -1.01106153, -0.97784704],
       [-0.38879623, -0.58907412, -0.11406505,  1.28400031]])

In [80]:
print(names)
names == 'Pedro'

['Pedro' 'Goncalo' 'Maria' 'Maria' 'Pedro' 'Joao' 'Pedro']


array([ True, False, False, False,  True, False,  True])

In [81]:
data[names == 'Pedro']

array([[ 2.83436822, -0.39655303,  0.22610492, -0.77144254],
       [ 0.72924946, -1.30924418,  0.32784375, -0.65750778],
       [-0.38879623, -0.58907412, -0.11406505,  1.28400031]])

In [82]:
data[names == 'Goncalo']

array([[-0.63763841, -0.43784856, -0.35788553, -0.02061979]])

In [83]:
data[names == 'Pedro', 2:]

array([[ 0.22610492, -0.77144254],
       [ 0.32784375, -0.65750778],
       [-0.11406505,  1.28400031]])

In [84]:
data[names == 'Pedro', 3]

array([-0.77144254, -0.65750778,  1.28400031])

In [85]:
data[names != 'Pedro']

array([[-0.63763841, -0.43784856, -0.35788553, -0.02061979],
       [ 0.83591948,  0.03121459,  1.07320361, -0.94190559],
       [ 0.36530313,  0.29042613,  0.4468085 , -1.47401516],
       [ 0.74913359, -0.99250194, -1.01106153, -0.97784704]])

In [86]:
data[~(names == 'Pedro')]  # boolean/binary negation

array([[-0.63763841, -0.43784856, -0.35788553, -0.02061979],
       [ 0.83591948,  0.03121459,  1.07320361, -0.94190559],
       [ 0.36530313,  0.29042613,  0.4468085 , -1.47401516],
       [ 0.74913359, -0.99250194, -1.01106153, -0.97784704]])

In [87]:
cond = names == 'Pedro'
data[~cond]

array([[-0.63763841, -0.43784856, -0.35788553, -0.02061979],
       [ 0.83591948,  0.03121459,  1.07320361, -0.94190559],
       [ 0.36530313,  0.29042613,  0.4468085 , -1.47401516],
       [ 0.74913359, -0.99250194, -1.01106153, -0.97784704]])

In [88]:
cond = (names == 'Pedro') | (names == 'Goncalo')  # '|' --> binary operation, not 'or'
data[cond]

array([[ 2.83436822, -0.39655303,  0.22610492, -0.77144254],
       [-0.63763841, -0.43784856, -0.35788553, -0.02061979],
       [ 0.72924946, -1.30924418,  0.32784375, -0.65750778],
       [-0.38879623, -0.58907412, -0.11406505,  1.28400031]])

In [89]:
data

array([[ 2.83436822, -0.39655303,  0.22610492, -0.77144254],
       [-0.63763841, -0.43784856, -0.35788553, -0.02061979],
       [ 0.83591948,  0.03121459,  1.07320361, -0.94190559],
       [ 0.36530313,  0.29042613,  0.4468085 , -1.47401516],
       [ 0.72924946, -1.30924418,  0.32784375, -0.65750778],
       [ 0.74913359, -0.99250194, -1.01106153, -0.97784704],
       [-0.38879623, -0.58907412, -0.11406505,  1.28400031]])

In [90]:
data[data > 0]

array([2.83436822, 0.22610492, 0.83591948, 0.03121459, 1.07320361,
       0.36530313, 0.29042613, 0.4468085 , 0.72924946, 0.32784375,
       0.74913359, 1.28400031])

In [91]:
data[data < 0] = 0
data

array([[2.83436822, 0.        , 0.22610492, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.83591948, 0.03121459, 1.07320361, 0.        ],
       [0.36530313, 0.29042613, 0.4468085 , 0.        ],
       [0.72924946, 0.        , 0.32784375, 0.        ],
       [0.74913359, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.28400031]])

In [92]:
#
# Arrays & Algebra
#

In [97]:
arr = np.arange(64).reshape((8, 8))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [98]:
arr.reshape((4, 4, 4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [101]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [112]:
arr[[1, 2, 4, -1]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [113]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [122]:
arr[[3, 0, -1]][:, [1, -2]]

array([[25, 30],
       [ 1,  6],
       [57, 62]])

In [123]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [125]:
arr.T  # transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [127]:
# matrix product
np.dot(arr, arr.T)  # 3,5 * 5,3  -->  3,3

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [129]:
np.dot(arr.T, arr)  # 5,3 * 3,5 --> 5,5


array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [130]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [131]:
arr.transpose((1, 0, 2))  # change axis --> extra mind bending --> ponto (0, 1, 0) ==> (1, 0, 0)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [132]:
arr.swapaxes(1, 2)  # shape 2, 4, 2

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [133]:
arr.swapaxes(1, 2)[0, 0, 1] = -5
arr

array([[[ 0,  1,  2,  3],
        [-5,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [134]:
# element-wise array functions

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [136]:
np.exp(arr)  # e^x

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [139]:
x = np.random.randn(5)
y = np.random.randn(5)
print(x)
print(y)
print(np.maximum(x, y))

[ 0.04737413 -0.3348141  -0.46656816  0.73167501 -1.11340661]
[ 0.55552015  0.5322588   0.98409445 -0.2357348  -0.42611129]
[ 0.55552015  0.5322588   0.98409445  0.73167501 -0.42611129]


'[ 0.55552015  0.5322588   0.98409445  0.73167501 -0.42611129]'

In [141]:
np.minimum(x, y)

array([ 0.04737413, -0.3348141 , -0.46656816, -0.2357348 , -1.11340661])

In [142]:
np.absolute(x)

array([0.04737413, 0.3348141 , 0.46656816, 0.73167501, 1.11340661])

In [144]:
decimal_part, int_part = np.modf(x)
print(decimal_part)
print(int_part)

[ 0.04737413 -0.3348141  -0.46656816  0.73167501 -0.11340661]
[ 0. -0. -0.  0. -1.]


In [146]:
np.sqrt(x, x)  # inplace operation

/tmp/ipykernel_7941/3507641013.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(x, x)


array([0.21765598,        nan,        nan, 0.85538004,        nan])

In [147]:
x

array([0.21765598,        nan,        nan, 0.85538004,        nan])

In [148]:
np.isnan(x)

array([False,  True,  True, False,  True])

In [149]:
x = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result = [elem_x if elem_cond else elem_y for elem_x, elem_y, elem_cond in zip(x, y, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [150]:
np.where(cond, x, y)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [151]:
arr = np.random.randn(4, 4)
arr

array([[ 0.27255318,  0.16016978, -1.86072097, -1.82514537],
       [ 0.34821   , -1.13129927, -0.41141203, -1.83891253],
       [ 1.09444793, -1.7871343 ,  0.25456698,  2.05792531],
       [-0.24894015, -0.43015806,  0.64249572, -1.37750965]])

In [152]:
arr > 0

array([[ True,  True, False, False],
       [ True, False, False, False],
       [ True, False,  True,  True],
       [False, False,  True, False]])

In [155]:
np.where(arr > 0, 1, 0)

array([[1, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 0]])

In [156]:
np.where(arr > 0, arr, 0)

array([[0.27255318, 0.16016978, 0.        , 0.        ],
       [0.34821   , 0.        , 0.        , 0.        ],
       [1.09444793, 0.        , 0.25456698, 2.05792531],
       [0.        , 0.        , 0.64249572, 0.        ]])

In [157]:
arr

array([[ 0.27255318,  0.16016978, -1.86072097, -1.82514537],
       [ 0.34821   , -1.13129927, -0.41141203, -1.83891253],
       [ 1.09444793, -1.7871343 ,  0.25456698,  2.05792531],
       [-0.24894015, -0.43015806,  0.64249572, -1.37750965]])

In [158]:
arr.mean()

-0.3800539653945543

In [159]:
arr.sum()

-6.080863446312869

In [160]:
arr.mean(axis=0)  # mean over the axis, so axis=0 => across the rows => mean of a column

array([ 0.36656774, -0.79710546, -0.34376757, -0.74591056])

In [161]:
arr.sum(axis=1)

array([-3.25314339, -3.03341382,  1.6198059 , -1.41411213])

In [162]:
np.arange(10).cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [164]:
np.arange(1, 11).cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [165]:
arr

array([[ 0.27255318,  0.16016978, -1.86072097, -1.82514537],
       [ 0.34821   , -1.13129927, -0.41141203, -1.83891253],
       [ 1.09444793, -1.7871343 ,  0.25456698,  2.05792531],
       [-0.24894015, -0.43015806,  0.64249572, -1.37750965]])

In [166]:
bools = arr > 0
bools

array([[ True,  True, False, False],
       [ True, False, False, False],
       [ True, False,  True,  True],
       [False, False,  True, False]])

In [167]:
bools.any()

True

In [168]:
bools.all()

False

In [174]:
(np.where(arr > 0, arr, 0) < 0).any()

False

In [175]:
arr

array([[ 0.27255318,  0.16016978, -1.86072097, -1.82514537],
       [ 0.34821   , -1.13129927, -0.41141203, -1.83891253],
       [ 1.09444793, -1.7871343 ,  0.25456698,  2.05792531],
       [-0.24894015, -0.43015806,  0.64249572, -1.37750965]])

In [176]:
arr.sort()

In [177]:
arr

array([[-1.86072097, -1.82514537,  0.16016978,  0.27255318],
       [-1.83891253, -1.13129927, -0.41141203,  0.34821   ],
       [-1.7871343 ,  0.25456698,  1.09444793,  2.05792531],
       [-1.37750965, -0.43015806, -0.24894015,  0.64249572]])

In [179]:
arr.sort(0)
arr

array([[-1.86072097, -1.82514537, -0.41141203,  0.27255318],
       [-1.83891253, -1.13129927, -0.24894015,  0.34821   ],
       [-1.7871343 , -0.43015806,  0.16016978,  0.64249572],
       [-1.37750965,  0.25456698,  1.09444793,  2.05792531]])

In [180]:
#
# More linear algebra
#


In [181]:
arr = np.arange(6).reshape(2, 3)
print(np.dot(arr, np.ones(3)))  # 2,3 * 3,1  => 2,1
print(arr.dot(np.ones(3)))
print(arr @ np.ones(3))  

[ 3. 12.]
[ 3. 12.]
[ 3. 12.]


In [182]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [183]:
my_arr = arr @ arr.T  # 2,3 * 3,2  => 2,2
my_arr

array([[ 5, 14],
       [14, 50]])

In [185]:
inverse_m = np.linalg.inv(my_arr)

In [186]:
my_arr @ inverse_m

array([[ 1.00000000e+00, -1.94289029e-16],
       [-7.77156117e-16,  1.00000000e+00]])

In [188]:
np.linalg.qr(my_arr)

(array([[-0.3363364 , -0.94174191],
        [-0.94174191,  0.3363364 ]]),
 array([[-14.86606875, -51.79580514],
        [  0.        ,   3.63243309]]))

In [189]:
#
#
#  PANDAS basics
#
#

In [190]:
import pandas as pd

In [191]:
obj = pd.Series([2, -3, 5, 100])
obj

0      2
1     -3
2      5
3    100
dtype: int64

In [192]:
print(obj.values, type(obj.values))

[  2  -3   5 100] <class 'numpy.ndarray'>


In [193]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [194]:
obj = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
obj

a    1
b    2
c    3
d    4
dtype: int64

In [195]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [196]:
obj['a']

1

In [197]:
obj.a

1

In [198]:
obj['c'] = 100
obj

a      1
b      2
c    100
d      4
dtype: int64

In [199]:
obj > 3

a    False
b    False
c     True
d     True
dtype: bool

In [200]:
obj[obj > 3]

c    100
d      4
dtype: int64

In [201]:
obj*2

a      2
b      4
c    200
d      8
dtype: int64

In [202]:
obj / 2

a     0.5
b     1.0
c    50.0
d     2.0
dtype: float64

In [203]:
np.exp(obj)

a    2.718282e+00
b    7.389056e+00
c    2.688117e+43
d    5.459815e+01
dtype: float64

In [204]:
'a' in obj

True

In [205]:
'e' in obj

False

In [206]:
obj['e'] = 10

In [207]:
obj

a      1
b      2
c    100
d      4
e     10
dtype: int64

In [208]:
some_data = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj1 = pd.Series(some_data)
obj1

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [210]:
states = ['California', 'Ohio', 'New York', 'Texas']
obj2 = pd.Series(some_data, index=states)
obj2

California        NaN
Ohio          35000.0
New York          NaN
Texas         71000.0
dtype: float64

In [217]:
obj2[obj2.notnull()]

Ohio     35000.0
Texas    71000.0
dtype: float64